FROM python:3.11.5

COPY file-converter.py /app/file-converter.py
COPY postulaciones.xlsx /app/postulaciones.xlsx

RUN pip install pandas cassandra-driver

WORKDIR /app

CMD ["python", "file-converter.py"]
